// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "DNS Resolver": resolve Resource Client
//
// Command:
// $ goagen
// --design=github.com/mtenrero/dockerDnsrr-discovery/design
// --out=$(GOPATH)/src/github.com/mtenrero/dockerDnsrr-discovery
// --version=v1.3.1

package client

import (
	"context"
	"fmt"
	"net/http"
	"net/url"
)

// ResolveResolvePath computes a request path to the resolve action of resolve.
func ResolveResolvePath(hostname string) string {
	param0 := hostname

	return fmt.Sprintf("/api/%s", param0)
}

// Resolves IPs from a specified hostname
func (c *Client) ResolveResolve(ctx context.Context, path string) (*http.Response, error) {
	req, err := c.NewResolveResolveRequest(ctx, path)
	if err != nil {
		return nil, err
	}
	return c.Client.Do(ctx, req)
}

// NewResolveResolveRequest create the request corresponding to the resolve action endpoint of the resolve resource.
func (c *Client) NewResolveResolveRequest(ctx context.Context, path string) (*http.Request, error) {
	scheme := c.Scheme
	if scheme == "" {
		scheme = "http"
	}
	u := url.URL{Host: c.Host, Scheme: scheme, Path: path}
	req, err := http.NewRequest("GET", u.String(), nil)
	if err != nil {
		return nil, err
	}
	return req, nil
}
