// Code generated by goagen v1.3.1, DO NOT EDIT.
//
// API "DNS Resolver": Application Resource Href Factories
//
// Command:
// $ goagen
// --design=github.com/mtenrero/dockerDnsrr-discovery/design
// --out=$(GOPATH)/src/github.com/mtenrero/dockerDnsrr-discovery
// --version=v1.3.1

package app
