package design

import (
	. "github.com/goadesign/goa/design/apidsl"
)

var _ = API("DNS Resolver", func() { // "My API" is the name of the API used in docs
	Title("ADNS Resolver")                               // Documentation title
	Description("REST Interface for DNS IPs resolution") // Longer documentation description
	Host("localhost:9090")                               // Host used by Swagger and clients
	Scheme("http")                                       // HTTP scheme used by Swagger and clients
	BasePath("/api")                                     // Base path to all API endpoints
	Consumes("application/json")                         // Media types supported by the API
	Produces("application/json")                         // Media types generated by the API
})
